import type { HomepageLanguage } from "@/content/homepage";
import { contactInfo, publicAddress } from "@/config/contactInfo";

export type LegalKey = "impressum" | "datenschutz" | "terms";
type Section = { heading: string; paragraphs: string[] };
type LegalCopy = { metaTitle: string; metaDescription: string; title: string; updated: string; sections: Section[] };

const soon = { de: "Angaben folgen in Kürze.", en: "Information coming soon." };
const company = (l: HomepageLanguage) => `${contactInfo.legalName}\n${publicAddress(l)}`;

export const legalPages: Record<LegalKey, { path: string; copy: Record<HomepageLanguage, LegalCopy> }> = {
  impressum: {
    path: "/impressum",
    copy: {
      de: {
        metaTitle: "Impressum — Empria Tech", metaDescription: "Impressum und Anbieterkennzeichnung von Empria Tech (MEDIA MARKETING LTD), London.", title: "Impressum", updated: "Stand: Oktober 2026",
        sections: [
          { heading: "Angaben gemäß § 5 DDG", paragraphs: [company("de"), "Empria Tech ist eine Marke der MEDIA MARKETING LTD."] },
          { heading: "Vertreten durch", paragraphs: [soon.de] },
          { heading: "Kontakt", paragraphs: [`E-Mail: ${contactInfo.email}`, `Telefon: ${contactInfo.phone}`] },
          { heading: "Registereintrag", paragraphs: ["Registerbehörde: Companies House, Vereinigtes Königreich", `Unternehmensnummer: ${contactInfo.companyNumber}`] },
          { heading: "Umsatzsteuer-ID", paragraphs: [`Umsatzsteuer-Identifikationsnummer gemäß § 27a UStG: ${soon.de}`] },
          { heading: "Tätigkeitsbereich", paragraphs: ["Webdesign, Google SEO (Suchmaschinenoptimierung), Digital Marketing und App-Entwicklung für Unternehmen."] },
          { heading: "Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV", paragraphs: [soon.de] },
          { heading: "EU-Streitschlichtung", paragraphs: ["Die Europäische Kommission stellte eine Plattform zur Online-Streitbeilegung (OS) bereit. Unsere E-Mail-Adresse finden Sie oben im Impressum."] },
          { heading: "Verbraucherstreitbeilegung / Universalschlichtungsstelle", paragraphs: ["Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen."] },
          { heading: "Haftung für Inhalte", paragraphs: ["Als Diensteanbieter sind wir für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Wir sind jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Bei Bekanntwerden von Rechtsverletzungen werden wir diese Inhalte umgehend entfernen."] },
          { heading: "Haftung für Links", paragraphs: ["Unser Angebot kann Links zu externen Websites Dritter enthalten, auf deren Inhalte wir keinen Einfluss haben. Für diese fremden Inhalte ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen."] },
          { heading: "Urheberrecht", paragraphs: ["Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers."] },
        ],
      },
      en: {
        metaTitle: "Legal notice — Empria Tech", metaDescription: "Legal notice (Impressum) of Empria Tech (MEDIA MARKETING LTD), London.", title: "Legal notice (Impressum)", updated: "Last updated: October 2026",
        sections: [
          { heading: "Information pursuant to § 5 DDG", paragraphs: [company("en"), "Empria Tech is a brand of MEDIA MARKETING LTD."] },
          { heading: "Represented by", paragraphs: [soon.en] },
          { heading: "Contact", paragraphs: [`Email: ${contactInfo.email}`, `Phone: ${contactInfo.phone}`] },
          { heading: "Register entry", paragraphs: ["Register authority: Companies House, United Kingdom", `Company number: ${contactInfo.companyNumber}`] },
          { heading: "VAT ID", paragraphs: [`VAT identification number pursuant to § 27a UStG: ${soon.en}`] },
          { heading: "Business activities", paragraphs: ["Web design, Google SEO (search engine optimization), digital marketing and app development for businesses."] },
          { heading: "Responsible for content pursuant to § 18 (2) MStV", paragraphs: [soon.en] },
          { heading: "EU dispute resolution", paragraphs: ["The European Commission provided a platform for online dispute resolution (ODR). Our email address can be found above."] },
          { heading: "Consumer dispute resolution", paragraphs: ["We are neither willing nor obliged to participate in dispute resolution proceedings before a consumer arbitration board."] },
          { heading: "Liability for content", paragraphs: ["As a service provider, we are responsible for our own content on these pages under general law. We are not obliged to monitor transmitted or stored third-party information. If we become aware of legal violations, we will remove such content immediately."] },
          { heading: "Liability for links", paragraphs: ["Our website may contain links to external third-party websites over whose content we have no control. The respective provider or operator is always responsible for that content. If we become aware of legal violations, we will remove such links immediately."] },
          { heading: "Copyright", paragraphs: ["Content and works created by the site operators are subject to German copyright law. Reproduction, editing, distribution and any kind of use beyond the limits of copyright law require the written consent of the respective author or creator."] },
        ],
      },
    },
  },
  datenschutz: {
    path: "/datenschutz",
    copy: {
      de: {
        metaTitle: "Datenschutzerklärung — Empria Tech", metaDescription: "Datenschutzerklärung von Empria Tech (MEDIA MARKETING LTD): Informationen zur Verarbeitung personenbezogener Daten gemäß DSGVO.", title: "Datenschutzerklärung", updated: "Stand: Oktober 2026",
        sections: [
          { heading: "1. Verantwortlicher", paragraphs: [company("de"), `Unternehmensnummer: ${contactInfo.companyNumber}`, `Telefon: ${contactInfo.phone}`, `E-Mail: ${contactInfo.email}`, "MEDIA MARKETING LTD betreibt die Marke Empria Tech und bietet Geschäftskunden Softwareentwicklung und Digital-Marketing-Leistungen. Wir entwickeln Websites und webbasierte Unternehmenssoftware und bieten SEO, Online-Werbung, Website-Management sowie damit verbundene Digital-Marketing-Leistungen.", `Datenschutzanfragen und die Ausübung von Betroffenenrechten können an ${contactInfo.email} gerichtet werden.`, "Nach unserer derzeitigen Einschätzung besteht keine gesetzliche Verpflichtung zur Benennung eines Datenschutzbeauftragten; daher wurde kein Datenschutzbeauftragter bestellt. Sollte sich die rechtliche oder tatsächliche Situation ändern, wird diese Angabe entsprechend aktualisiert."] },
          { heading: "2. Allgemeines", paragraphs: ["Wir nehmen den Schutz Ihrer personenbezogenen Daten ernst und verarbeiten diese ausschließlich im Rahmen der gesetzlichen Bestimmungen, insbesondere der Datenschutz-Grundverordnung (DSGVO) und des Bundesdatenschutzgesetzes (BDSG)."] },
          { heading: "3. Hosting und Server-Logfiles", paragraphs: ["Beim Aufruf unserer Website werden durch den Hosting-Anbieter automatisch Informationen erfasst, die Ihr Browser übermittelt: IP-Adresse, Datum und Uhrzeit, aufgerufene Seite, Referrer-URL, Browsertyp und Betriebssystem. Diese Daten dienen der sicheren und stabilen Bereitstellung der Website. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO.", `Hosting-Anbieter: ${soon.de}`] },
          { heading: "4. Kontaktformular und E-Mail", paragraphs: ["Wenn Sie uns über das Kontaktformular oder per E-Mail kontaktieren, verarbeiten wir die angegebenen Daten (z. B. Name, E-Mail-Adresse, Unternehmen, Nachricht) ausschließlich zur Bearbeitung Ihrer Anfrage. Die Anfrage wird per E-Mail an uns übermittelt. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (vorvertragliche Maßnahmen) bzw. lit. f DSGVO (berechtigtes Interesse an der Beantwortung). Die Daten werden gelöscht, sobald sie nicht mehr erforderlich sind und keine gesetzlichen Aufbewahrungspflichten bestehen."] },
          { heading: "5. Kundenkonto und Login", paragraphs: ["Für die Nutzung unseres Kundenbereichs ist eine Registrierung erforderlich. Dabei verarbeiten wir die von Ihnen angegebenen Daten (z. B. Name, E-Mail-Adresse, Passwort in verschlüsselter Form) sowie projekt- und auftragsbezogene Informationen zur Vertragserfüllung gemäß Art. 6 Abs. 1 lit. b DSGVO. Für die Anmeldung werden technisch notwendige Daten im Browser gespeichert."] },
          { heading: "6. Schriftarten (Google Fonts)", paragraphs: ["Diese Website lädt Schriftarten von Google Fonts (Google Ireland Limited). Dabei wird Ihre IP-Adresse an Google übermittelt. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO (einheitliche Darstellung). Weitere Informationen finden Sie in der Datenschutzerklärung von Google."] },
          { heading: "7. Lokale Speicherung im Browser", paragraphs: ["Wir speichern Ihre gewählte Sprache (Deutsch/Englisch) im lokalen Speicher Ihres Browsers. Es werden keine Tracking- oder Marketing-Cookies eingesetzt. Rechtsgrundlage ist § 25 Abs. 2 TDDDG."] },
          { heading: "8. Weitere eingesetzte Dienste", paragraphs: [soon.de] },
          { heading: "9. SSL- bzw. TLS-Verschlüsselung", paragraphs: ["Diese Seite nutzt aus Sicherheitsgründen eine SSL- bzw. TLS-Verschlüsselung. Eine verschlüsselte Verbindung erkennen Sie an „https://“ in der Adresszeile Ihres Browsers."] },
          { heading: "10. Speicherdauer", paragraphs: ["Personenbezogene Daten werden nur so lange gespeichert, wie es für den jeweiligen Zweck erforderlich ist oder gesetzliche Aufbewahrungsfristen (z. B. handels- und steuerrechtlich) bestehen."] },
          { heading: "11. Ihre Rechte", paragraphs: ["Sie haben das Recht auf Auskunft (Art. 15 DSGVO), Berichtigung (Art. 16), Löschung (Art. 17), Einschränkung der Verarbeitung (Art. 18), Datenübertragbarkeit (Art. 20) sowie Widerspruch gegen die Verarbeitung (Art. 21). Erteilte Einwilligungen können Sie jederzeit mit Wirkung für die Zukunft widerrufen.", "Sie haben außerdem das Recht, sich bei einer zuständigen Datenschutz-Aufsichtsbehörde zu beschweren.", `Zur Ausübung Ihrer Rechte genügt eine E-Mail an ${contactInfo.email}.`] },
          { heading: "12. Änderungen", paragraphs: ["Wir behalten uns vor, diese Datenschutzerklärung anzupassen, damit sie stets den aktuellen rechtlichen Anforderungen entspricht oder Änderungen unserer Leistungen abbildet."] },
        ],
      },
      en: {
        metaTitle: "Privacy policy — Empria Tech", metaDescription: "Privacy policy of Empria Tech (MEDIA MARKETING LTD): information on the processing of personal data under the GDPR.", title: "Privacy policy", updated: "Last updated: October 2026",
        sections: [
          { heading: "1. Controller", paragraphs: [company("en"), `Company number: ${contactInfo.companyNumber}`, `Phone: ${contactInfo.phone}`, `Email: ${contactInfo.email}`, "MEDIA MARKETING LTD operates the Empria Tech brand and provides software development and digital marketing services to business clients. We develop websites and web-based business software and provide SEO, online advertising, website management and related digital marketing services.", `Privacy enquiries and data-subject requests may be sent to ${contactInfo.email}.`, "Based on our current assessment, the company is not legally required to appoint a data protection officer, and none has therefore been appointed. This statement will be updated if the legal or factual circumstances change."] },
          { heading: "2. General", paragraphs: ["We take the protection of your personal data seriously and process it only in accordance with legal requirements, in particular the General Data Protection Regulation (GDPR) and the German Federal Data Protection Act (BDSG)."] },
          { heading: "3. Hosting and server log files", paragraphs: ["When you visit our website, the hosting provider automatically records information sent by your browser: IP address, date and time, page visited, referrer URL, browser type and operating system. This data is used to provide the website securely and reliably. The legal basis is Art. 6(1)(f) GDPR.", `Hosting provider: ${soon.en}`] },
          { heading: "4. Contact form and email", paragraphs: ["If you contact us via the contact form or by email, we process the data you provide (e.g. name, email address, company, message) solely to handle your enquiry. The enquiry is forwarded to us by email. The legal basis is Art. 6(1)(b) GDPR (pre-contractual measures) or Art. 6(1)(f) GDPR (legitimate interest in responding). The data is deleted once it is no longer needed and no statutory retention obligations apply."] },
          { heading: "5. Customer account and login", paragraphs: ["Using our client area requires registration. We process the data you provide (e.g. name, email address, password in encrypted form) as well as project and order information to perform the contract under Art. 6(1)(b) GDPR. Technically necessary data for signing in is stored in your browser."] },
          { heading: "6. Fonts (Google Fonts)", paragraphs: ["This website loads fonts from Google Fonts (Google Ireland Limited). Your IP address is transmitted to Google in the process. The legal basis is Art. 6(1)(f) GDPR (consistent presentation). Further information is available in Google's privacy policy."] },
          { heading: "7. Local browser storage", paragraphs: ["We store your selected language (German/English) in your browser's local storage. No tracking or marketing cookies are used. The legal basis is § 25(2) TDDDG."] },
          { heading: "8. Other services used", paragraphs: [soon.en] },
          { heading: "9. SSL/TLS encryption", paragraphs: ["For security reasons this site uses SSL/TLS encryption. You can recognise an encrypted connection by “https://” in your browser's address bar."] },
          { heading: "10. Retention period", paragraphs: ["Personal data is stored only as long as required for the relevant purpose or as long as statutory retention periods (e.g. commercial and tax law) apply."] },
          { heading: "11. Your rights", paragraphs: ["You have the right of access (Art. 15 GDPR), rectification (Art. 16), erasure (Art. 17), restriction of processing (Art. 18), data portability (Art. 20) and objection (Art. 21). You may withdraw any consent at any time with effect for the future.", "You also have the right to lodge a complaint with a competent data protection supervisory authority.", `To exercise your rights, simply email ${contactInfo.email}.`] },
          { heading: "12. Changes", paragraphs: ["We may update this privacy policy so that it always meets current legal requirements or reflects changes to our services."] },
        ],
      },
    },
  },
  terms: {
    path: "/terms",
    copy: {
      de: {
        metaTitle: "Geschäftsbedingungen — Empria Tech", metaDescription: "Allgemeine Geschäftsbedingungen für B2B-Leistungen von Empria Tech, betrieben durch MEDIA MARKETING LTD.", title: "Geschäftsbedingungen", updated: "Stand: Oktober 2026 · Allgemeine Vorlage zur rechtlichen Prüfung",
        sections: [
          { heading: "1. Anbieter und Geltungsbereich", paragraphs: [company("de"), `Unternehmensnummer: ${contactInfo.companyNumber}`, `E-Mail: ${contactInfo.email} · Telefon: ${contactInfo.phone}`, "Empria Tech wird von MEDIA MARKETING LTD betrieben. Diese Geschäftsbedingungen gelten ausschließlich für Verträge mit Unternehmen und sonstigen Geschäftskunden, soweit im jeweiligen Angebot oder Vertrag nichts anderes vereinbart ist."] },
          { heading: "2. Leistungen", paragraphs: ["Wir erbringen insbesondere Webentwicklung, webbasierte Unternehmenssoftware, SEO, Online-Werbung, Website-Management, Digital Marketing und damit verbundene Wartungsleistungen. Der konkrete Leistungsumfang, Zeitplan und die Ergebnisse ergeben sich aus dem jeweiligen Angebot, Auftrag oder Vertrag."] },
          { heading: "3. Angebot und Vertragsschluss", paragraphs: ["Ein Vertrag kommt durch Annahme unseres Angebots, eine schriftliche Auftragsbestätigung oder den Beginn der vereinbarten Leistung auf Wunsch des Kunden zustande. Individuelle Vereinbarungen im Angebot oder Vertrag haben Vorrang vor diesen allgemeinen Bedingungen."] },
          { heading: "4. Mitwirkung des Kunden", paragraphs: ["Der Kunde stellt rechtzeitig vollständige Inhalte, Zugänge, Freigaben und sonstige erforderliche Informationen bereit. Verzögerungen oder Mehraufwand aufgrund verspäteter, unvollständiger oder fehlerhafter Mitwirkung können Termin und Vergütung beeinflussen."] },
          { heading: "5. Durchführung, Abnahme und Änderungen", paragraphs: ["Wir erbringen Leistungen nach dem vereinbarten Umfang. Der Kunde prüft bereitgestellte Ergebnisse innerhalb einer angemessenen Frist und meldet konkrete wesentliche Mängel. Änderungen oder zusätzliche Leistungen außerhalb des vereinbarten Umfangs können gesondert angeboten und berechnet werden. Eine feste Abnahmefrist folgt in Kürze."] },
          { heading: "6. Vergütung und Zahlung", paragraphs: ["Sofern im jeweiligen Angebot oder Vertrag keine Meilensteine oder abweichenden Zahlungsbedingungen vereinbart sind, wird die Rechnung nach Erbringung der vereinbarten Leistung ausgestellt. Rechnungen sind innerhalb von 14 Kalendertagen ab Rechnungsdatum ohne Abzug per Banküberweisung auf das in der Rechnung angegebene Konto zu zahlen. Individuell vereinbarte Zahlungsbedingungen haben Vorrang. Gesetzliche Rechte bei Zahlungsverzug bleiben unberührt."] },
          { heading: "7. Wiederkehrende Leistungen", paragraphs: ["Wartung, Website-Management, SEO, Werbung und andere laufende Leistungen werden für die jeweils vereinbarte Laufzeit erbracht. Verlängerung, Kündigungsfrist und Leistungsumfang richten sich nach dem jeweiligen Vertrag. Allgemeine Kündigungsfristen folgen in Kürze."] },
          { heading: "8. Drittanbieter und Werbebudgets", paragraphs: ["Kosten für Domains, Hosting, Werbebudgets, Plattformen, Lizenzen, Stockmedien und andere Drittanbieter sind nur enthalten, wenn dies ausdrücklich vereinbart wurde. Verfügbarkeit, Richtlinien und Entscheidungen externer Plattformen liegen außerhalb unserer Kontrolle."] },
          { heading: "9. Rechte an Arbeitsergebnissen", paragraphs: ["Nutzungs- und Eigentumsrechte an Designs, Quellcode, Inhalten und sonstigen Arbeitsergebnissen richten sich nach dem jeweiligen Angebot oder Vertrag und gehen, soweit vereinbart, erst nach vollständiger Zahlung über. Rechte an vorbestehenden Werkzeugen, Bibliotheken und Drittanbieterkomponenten verbleiben bei ihren jeweiligen Rechteinhabern. Detaillierte Standard-Lizenzregeln folgen in Kürze."] },
          { heading: "10. Kundenseitige Inhalte", paragraphs: ["Der Kunde gewährleistet, dass bereitgestellte Texte, Bilder, Marken, Daten und Zugänge rechtmäßig verwendet werden dürfen und keine Rechte Dritter verletzen. Der Kunde bleibt für die Rechtmäßigkeit seiner geschäftlichen Inhalte und Werbeaussagen verantwortlich."] },
          { heading: "11. Vertraulichkeit und Datenschutz", paragraphs: ["Beide Parteien behandeln vertrauliche geschäftliche Informationen angemessen geschützt. Personenbezogene Daten verarbeiten wir gemäß unserer Datenschutzerklärung und, falls erforderlich, einer gesonderten Vereinbarung zur Auftragsverarbeitung."] },
          { heading: "12. Verfügbarkeit, Support und Gewährleistung", paragraphs: ["Wir erbringen unsere Leistungen mit angemessener fachlicher Sorgfalt. Allgemeine Supportanfragen werden montags bis freitags während der üblichen Geschäftszeiten, ausgenommen gesetzliche Feiertage, bearbeitet. Eine bestimmte Reaktions- oder Lösungszeit gilt nur, wenn sie in einem Angebot, Wartungspaket oder Servicevertrag ausdrücklich vereinbart wurde.", "Der allgemeine Support umfasst nur den vereinbarten Leistungsumfang. Zusätzliche Arbeiten, neue Funktionen, Ausfälle von Drittanbietern und vom Kunden verursachte Probleme können gesondert angeboten und berechnet werden. Notfallbereitschaft, Verfügbarkeitszusagen und Service Levels gelten nur bei ausdrücklicher vertraglicher Vereinbarung.", "Eine unterbrechungsfreie Verfügbarkeit, bestimmte Suchmaschinenplatzierungen oder konkrete Werbe- und Geschäftsergebnisse werden nur geschuldet, wenn dies ausdrücklich schriftlich vereinbart wurde."] },
          { heading: "13. Haftung", paragraphs: ["Die Haftung richtet sich nach den zwingenden gesetzlichen Vorschriften und den individuellen Vereinbarungen. Eine weitergehende Haftungsregelung, einschließlich etwaiger Haftungsgrenzen, folgt nach rechtlicher Prüfung."] },
          { heading: "14. Aussetzung und Beendigung", paragraphs: ["Bei erheblichem Zahlungsverzug, Sicherheitsrisiken, rechtswidriger Nutzung oder schwerwiegenden Vertragsverletzungen können Leistungen nach angemessener Ankündigung ausgesetzt werden, soweit rechtlich zulässig. Kündigung, Folgen der Beendigung und Rückerstattungen richten sich nach dem jeweiligen Vertrag; allgemeine Regeln folgen in Kürze."] },
          { heading: "15. Recht und Gerichtsstand", paragraphs: ["Diese Geschäftsbedingungen und die darunter geschlossenen B2B-Verträge unterliegen dem Recht von England und Wales. Für Streitigkeiten sind die Gerichte von England und Wales ausschließlich zuständig, soweit keine zwingenden gesetzlichen Vorschriften entgegenstehen oder im individuellen Vertrag ausdrücklich etwas anderes vereinbart wurde."] },
          { heading: "16. Schlussbestimmungen", paragraphs: ["Sollte eine Bestimmung unwirksam sein, bleiben die übrigen Bestimmungen unberührt, soweit gesetzlich zulässig. Individuelle Vereinbarungen und zwingende gesetzliche Rechte gehen diesen Bedingungen vor."] },
        ],
      },
      en: {
        metaTitle: "Terms and Conditions — Empria Tech", metaDescription: "General B2B Terms and Conditions for Empria Tech services operated by MEDIA MARKETING LTD.", title: "Terms and Conditions", updated: "Last updated: October 2026 · General template pending legal review",
        sections: [
          { heading: "1. Provider and scope", paragraphs: [company("en"), `Company number: ${contactInfo.companyNumber}`, `Email: ${contactInfo.email} · Phone: ${contactInfo.phone}`, "Empria Tech is operated by MEDIA MARKETING LTD. These Terms apply exclusively to contracts with companies and other business clients unless an individual proposal or contract states otherwise."] },
          { heading: "2. Services", paragraphs: ["We provide web development, web-based business software, SEO, online advertising, website management, digital marketing and related maintenance services. The specific scope, schedule and deliverables are defined in the applicable proposal, order or contract."] },
          { heading: "3. Proposals and contract formation", paragraphs: ["A contract is formed when our proposal is accepted, we issue written order confirmation, or we begin the agreed work at the client's request. Individual terms in a proposal or contract take priority over these general Terms."] },
          { heading: "4. Client cooperation", paragraphs: ["The client must provide complete content, access, approvals and other required information on time. Delay or additional work caused by late, incomplete or inaccurate cooperation may affect the schedule and fees."] },
          { heading: "5. Delivery, acceptance and changes", paragraphs: ["We deliver the agreed scope. The client should review deliverables within a reasonable period and report specific material defects. Changes or extra work outside the agreed scope may be quoted and charged separately. A standard acceptance period is coming soon."] },
          { heading: "6. Fees and payment", paragraphs: ["Unless the applicable proposal or contract specifies milestones or different payment terms, an invoice is issued after the agreed services have been provided. Invoices are payable by bank transfer within 14 calendar days of the invoice date, without deduction, to the account stated on the invoice. Individually agreed payment terms take priority. Statutory rights in case of late payment remain unaffected."] },
          { heading: "7. Recurring services", paragraphs: ["Maintenance, website management, SEO, advertising and other ongoing services are supplied for the agreed term. Renewal, notice period and scope are governed by the applicable contract. Standard termination periods are coming soon."] },
          { heading: "8. Third parties and advertising budgets", paragraphs: ["Domains, hosting, advertising spend, platforms, licences, stock media and other third-party costs are included only when expressly agreed. External platform availability, policies and decisions remain outside our control."] },
          { heading: "9. Rights in deliverables", paragraphs: ["Ownership and usage rights in designs, source code, content and other deliverables are governed by the applicable proposal or contract and, where agreed, transfer only after full payment. Rights in pre-existing tools, libraries and third-party components remain with their respective owners. Detailed standard licensing rules are coming soon."] },
          { heading: "10. Client-provided materials", paragraphs: ["The client warrants that supplied text, images, brands, data and access may lawfully be used and do not infringe third-party rights. The client remains responsible for the legality of its business content and advertising claims."] },
          { heading: "11. Confidentiality and data protection", paragraphs: ["Both parties will appropriately protect confidential business information. We process personal data under our Privacy Policy and, where required, a separate data-processing agreement."] },
          { heading: "12. Availability, support and warranty", paragraphs: ["We provide services with reasonable professional care. General support requests are handled Monday to Friday during normal business hours, excluding public holidays. No specific response or resolution time applies unless expressly agreed in a proposal, maintenance plan or service agreement.", "General support covers only the agreed service scope. Additional work, new features, third-party failures and client-caused issues may be quoted and charged separately. Emergency coverage, uptime commitments and service levels apply only where expressly agreed by contract.", "Uninterrupted availability, specific search rankings, or particular advertising and business outcomes are guaranteed only when expressly agreed in writing."] },
          { heading: "13. Liability", paragraphs: ["Liability is governed by mandatory law and the individual agreement. More detailed liability provisions, including any permissible limits, will be added after legal review."] },
          { heading: "14. Suspension and termination", paragraphs: ["In cases of material non-payment, security risks, unlawful use or serious contract breach, services may be suspended after reasonable notice where legally permitted. Termination, its effects and refunds are governed by the applicable contract; standard rules are coming soon."] },
          { heading: "15. Governing law and jurisdiction", paragraphs: ["These Terms and B2B contracts concluded under them are governed by the laws of England and Wales. The courts of England and Wales have exclusive jurisdiction over disputes, unless mandatory law requires otherwise or the individual contract expressly agrees different terms."] },
          { heading: "16. Final provisions", paragraphs: ["If a provision is unenforceable, the remaining provisions continue to apply where legally permitted. Individual agreements and mandatory legal rights take priority over these Terms."] },
        ],
      },
    },
  },
};
