import webImage from "@/assets/empria-webdesign-studio.jpg";
import seoImage from "@/assets/empria-seo-analysis.jpg";
import marketingImage from "@/assets/empria-digital-marketing.jpg";
import appImage from "@/assets/empria-app-development.jpg";
import type { HomepageLanguage } from "@/content/homepage";

export type ServiceKey = "webdesign" | "googleSeo" | "digitalMarketing" | "appDevelopment";

type LocalizedService = {
  metaTitle: string; metaDescription: string; eyebrow: string; title: string; accent: string; intro: string; imageAlt: string;
  primary: string; overviewEyebrow: string; overviewTitle: string; overviewBody: string;
  capabilities: Array<{ title: string; body: string }>;
  deliverablesEyebrow: string; deliverablesTitle: string; deliverables: string[];
  processEyebrow: string; processTitle: string; process: Array<{ number: string; title: string; body: string }>;
  outcomesEyebrow: string; outcomesTitle: string; outcomesBody: string; outcomes: Array<{ title: string; body: string }>;
  relatedEyebrow: string; relatedTitle: string; faqEyebrow: string; faqTitle: string; faqs: Array<{ question: string; answer: string }>;
  ctaTitle: string; ctaBody: string; ctaPrimary: string; ctaSecondary: string;
};

export type ServiceDefinition = { path: string; image: string; related: ServiceKey[]; copy: Record<HomepageLanguage, LocalizedService> };

export const servicePages: Record<ServiceKey, ServiceDefinition> = {
  webdesign: {
    path: "/webdesign", image: webImage, related: ["googleSeo", "digitalMarketing"],
    copy: {
      de: {
        metaTitle: "Professionelles Webdesign — Empria Tech", metaDescription: "Individuelles Webdesign von Empria Tech: Strategie, UX/UI, responsive Entwicklung, Performance und klare Nutzerführung für Unternehmen.",
        eyebrow: "Empria Tech · Webdesign", title: "Professionelles Webdesign", accent: "für einen Auftritt mit Substanz.", intro: "Wir entwickeln Unternehmenswebsites, die Ihre Positionierung verständlich machen, Vertrauen aufbauen und Besucher sicher zum nächsten Schritt führen.", imageAlt: "Professionelle Unternehmenswebsite in Desktop- und Mobilansicht", primary: "Webdesign-Projekt starten",
        overviewEyebrow: "Mehr als eine schöne Oberfläche", overviewTitle: "Webdesign, das Strategie, Inhalt und Technik verbindet.", overviewBody: "Eine Website ist oft der erste vertiefte Kontakt mit Ihrem Unternehmen. Deshalb beginnt unser Prozess nicht mit Farben, sondern mit Zielen, Zielgruppen und der Frage, welche Informationen Menschen für eine Entscheidung benötigen.",
        capabilities: [{ title: "Website-Strategie", body: "Ziele, Zielgruppen und zentrale Nutzerwege bilden das Fundament." }, { title: "Informationsarchitektur", body: "Leistungen und Inhalte werden verständlich priorisiert und gegliedert." }, { title: "UX & UI Design", body: "Klare Bedienung trifft auf eine eigenständige, professionelle Markenwirkung." }, { title: "Responsive Entwicklung", body: "Der Auftritt funktioniert konsistent auf Smartphone, Tablet und Desktop." }, { title: "Conversion-orientierte Seiten", body: "Kontaktpunkte und nächste Schritte sind sichtbar, sinnvoll und nicht aufdringlich." }, { title: "Technische Qualität", body: "Saubere Umsetzung schafft eine belastbare Basis für Performance und SEO." }],
        deliverablesEyebrow: "Leistungsumfang", deliverablesTitle: "Bausteine für eine belastbare Unternehmenswebsite.", deliverables: ["Strategische Seiten- und Inhaltsplanung", "Individuelles visuelles Konzept", "Responsive Seitenlayouts", "Komponenten und konsistentes Designsystem", "Technische Umsetzung und Qualitätsprüfung", "Grundlegende Suchmaschinen- und Performance-Optimierung"],
        processEyebrow: "Unser Webdesign-Prozess", processTitle: "Von der Positionierung bis zum veröffentlichten Auftritt.", process: [{ number: "01", title: "Analyse", body: "Wir verstehen Ihr Angebot, Ihre Zielgruppen und die Aufgabe der neuen Website." }, { number: "02", title: "Struktur", body: "Wir planen Seiten, Inhalte, Nutzerwege und die wichtigsten Kontaktpunkte." }, { number: "03", title: "Design", body: "Wir entwickeln die visuelle Sprache und übersetzen sie in responsive Ansichten." }, { number: "04", title: "Umsetzung", body: "Die Website wird entwickelt, geprüft und für einen sauberen Start vorbereitet." }],
        outcomesEyebrow: "Wirkung", outcomesTitle: "Ein professionelles digitales Fundament.", outcomesBody: "Das Ergebnis unterstützt Vertrieb und Kommunikation, ohne seine Aufgabe hinter visuellen Effekten zu verstecken.", outcomes: [{ title: "Schnell verständlich", body: "Besucher erkennen Angebot, Nutzen und nächste Schritte ohne Umwege." }, { title: "Vertrauenswürdig", body: "Gestaltung und Inhalt vermitteln Sorgfalt und Professionalität." }, { title: "Erweiterbar", body: "Die Struktur kann mit neuen Leistungen und Inhalten sinnvoll wachsen." }],
        relatedEyebrow: "Sinnvolle Ergänzungen", relatedTitle: "Design wird stärker durch Sichtbarkeit und Reichweite.", faqEyebrow: "Webdesign FAQ", faqTitle: "Häufige Fragen zum Website-Projekt.", faqs: [{ question: "Kann Empria Tech eine bestehende Website überarbeiten?", answer: "Ja. Nach einer Analyse kann eine bestehende Website gezielt verbessert oder strukturell neu aufgebaut werden." }, { question: "Ist SEO bereits im Webdesign enthalten?", answer: "Technische und strukturelle SEO-Grundlagen werden berücksichtigt. Eine umfassende Suchstrategie ist als eigene Leistung verfügbar." }, { question: "Ist die Website mobil optimiert?", answer: "Ja. Responsive Planung und Umsetzung gehören zum festen Leistungsumfang." }],
        ctaTitle: "Bereit für eine Website, die Ihr Unternehmen klar repräsentiert?", ctaBody: "Registrieren Sie sich und starten Sie Ihr Webdesign-Projekt mit Empria Tech.", ctaPrimary: "Projekt starten", ctaSecondary: "Anmelden",
      },
      en: {
        metaTitle: "Professional Web Design — Empria Tech", metaDescription: "Bespoke web design by Empria Tech: strategy, UX/UI, responsive development, performance and clear user journeys for businesses.",
        eyebrow: "Empria Tech · Web design", title: "Professional web design", accent: "for a presence with substance.", intro: "We create business websites that clarify your positioning, build trust and guide visitors confidently toward the next step.", imageAlt: "Professional business website shown on desktop and mobile", primary: "Start a web design project",
        overviewEyebrow: "More than a polished surface", overviewTitle: "Web design connecting strategy, content and technology.", overviewBody: "A website is often the first meaningful interaction with your company. Our process therefore starts with goals, audiences and the information people need to make a decision, not with colors.",
        capabilities: [{ title: "Website strategy", body: "Goals, audiences and core user journeys form the foundation." }, { title: "Information architecture", body: "Services and content are prioritized and structured clearly." }, { title: "UX & UI design", body: "Clear usability meets a distinctive, professional brand experience." }, { title: "Responsive development", body: "The experience remains consistent across mobile, tablet and desktop." }, { title: "Conversion-focused pages", body: "Contact points and next steps are visible, relevant and never intrusive." }, { title: "Technical quality", body: "Clean implementation creates a dependable base for performance and SEO." }],
        deliverablesEyebrow: "Scope", deliverablesTitle: "The building blocks of a dependable business website.", deliverables: ["Strategic page and content planning", "Bespoke visual concept", "Responsive page layouts", "Components and a consistent design system", "Technical implementation and quality review", "Foundational search and performance optimization"],
        processEyebrow: "Our web design process", processTitle: "From positioning to a published digital presence.", process: [{ number: "01", title: "Analyze", body: "We understand your offer, audiences and the job your new website must do." }, { number: "02", title: "Structure", body: "We plan pages, content, user journeys and the most important contact points." }, { number: "03", title: "Design", body: "We create the visual language and translate it into responsive views." }, { number: "04", title: "Build", body: "The website is developed, reviewed and prepared for a clean launch." }],
        outcomesEyebrow: "Impact", outcomesTitle: "A professional digital foundation.", outcomesBody: "The result supports sales and communication without hiding its purpose behind visual effects.", outcomes: [{ title: "Easy to understand", body: "Visitors recognize your offer, value and next steps without detours." }, { title: "Trustworthy", body: "Design and content communicate care and professionalism." }, { title: "Expandable", body: "The structure can grow naturally with new services and content." }],
        relatedEyebrow: "Related services", relatedTitle: "Design becomes stronger with visibility and reach.", faqEyebrow: "Web design FAQ", faqTitle: "Common questions about a website project.", faqs: [{ question: "Can Empria Tech improve an existing website?", answer: "Yes. Following an assessment, an existing website can be improved selectively or rebuilt around a clearer structure." }, { question: "Is SEO included in web design?", answer: "Technical and structural SEO foundations are considered. A comprehensive search strategy is available as a dedicated service." }, { question: "Will the website work on mobile?", answer: "Yes. Responsive planning and development are standard parts of the service." }],
        ctaTitle: "Ready for a website that represents your company clearly?", ctaBody: "Register and start your web design project with Empria Tech.", ctaPrimary: "Start a project", ctaSecondary: "Log in",
      },
    },
  },
  googleSeo: {
    path: "/google-seo", image: seoImage, related: ["webdesign", "digitalMarketing"],
    copy: {
      de: {
        metaTitle: "Google SEO für Unternehmen — Empria Tech", metaDescription: "Google SEO von Empria Tech: Keyword-Strategie, technisches SEO, On-Page-Inhalte und lokale Sichtbarkeit für nachhaltiges organisches Wachstum.",
        eyebrow: "Empria Tech · Google SEO", title: "Google SEO", accent: "für relevante organische Sichtbarkeit.", intro: "Wir schaffen die technische, strukturelle und inhaltliche Grundlage, damit Google Ihre Seiten versteht und potenzielle Kunden sie in den richtigen Suchmomenten finden.", imageAlt: "SEO-Analyse mit Keyword-Daten, technischen Berichten und organischen Trends", primary: "SEO-Projekt starten",
        overviewEyebrow: "Nachvollziehbare Suchstrategie", overviewTitle: "Sichtbarkeit beginnt mit Suchintention, nicht mit einzelnen Keywords.", overviewBody: "Wir betrachten, was Ihre Zielgruppe sucht, welche Fragen hinter einer Suchanfrage stehen und welche Seite die beste Antwort geben kann. Daraus entsteht eine priorisierte Strategie statt einer unverbundenen Liste von Maßnahmen.",
        capabilities: [{ title: "Keyword-Strategie", body: "Suchthemen werden nach Relevanz, Absicht und Geschäftswert geordnet." }, { title: "Technisches SEO", body: "Indexierbarkeit, interne Struktur und technische Signale werden geprüft." }, { title: "On-Page SEO", body: "Titel, Überschriften, Inhalte und interne Links erhalten eine klare Aufgabe." }, { title: "Content-Planung", body: "Relevante Seiten und Themen werden entlang realer Fragen entwickelt." }, { title: "Lokales SEO", body: "Standortbezogene Suchen und lokale Relevanz werden gezielt berücksichtigt." }, { title: "Auswertung", body: "Entwicklung und Prioritäten werden anhand nachvollziehbarer Signale überprüft." }],
        deliverablesEyebrow: "Leistungsumfang", deliverablesTitle: "Die wesentlichen Bausteine nachhaltiger SEO-Arbeit.", deliverables: ["Suchmarkt- und Wettbewerbsanalyse", "Keyword- und Themenstruktur", "Technische Bestandsaufnahme", "On-Page-Empfehlungen und Optimierung", "Inhaltsplanung nach Suchintention", "Priorisierte Weiterentwicklung"],
        processEyebrow: "Unser SEO-Prozess", processTitle: "Analysieren, priorisieren, umsetzen und weiterentwickeln.", process: [{ number: "01", title: "Ausgangslage", body: "Wir prüfen Website, Markt, Inhalte und bestehende organische Signale." }, { number: "02", title: "Suchstrategie", body: "Wir ordnen relevante Themen und definieren realistische Prioritäten." }, { number: "03", title: "Optimierung", body: "Technik, Seitenstruktur und Inhalte werden systematisch verbessert." }, { number: "04", title: "Weiterentwicklung", body: "Erkenntnisse fließen in neue Inhalte und die nächsten sinnvollen Maßnahmen ein." }],
        outcomesEyebrow: "Wirkung", outcomesTitle: "Bessere Voraussetzungen für organisches Wachstum.", outcomesBody: "SEO ist eine langfristige Disziplin. Wir versprechen keine feste Position, sondern schaffen eine belastbare Grundlage für relevante Sichtbarkeit.", outcomes: [{ title: "Besser verständlich", body: "Suchmaschinen können Themen, Beziehungen und Seitenzwecke klarer einordnen." }, { title: "Relevanter Inhalt", body: "Seiten orientieren sich an echten Fragen und Entscheidungen der Zielgruppe." }, { title: "Klare Prioritäten", body: "Maßnahmen folgen einer nachvollziehbaren Reihenfolge statt Einzelaktionen." }],
        relatedEyebrow: "Sinnvolle Ergänzungen", relatedTitle: "SEO entfaltet mehr Wirkung mit starker Website und Kampagnen.", faqEyebrow: "Google SEO FAQ", faqTitle: "Häufige Fragen zur Suchmaschinenoptimierung.", faqs: [{ question: "Garantiert SEO Platz 1 bei Google?", answer: "Nein. Rankings werden von vielen Faktoren beeinflusst. Seriöse SEO verbessert Chancen und Relevanz, garantiert aber keine feste Position." }, { question: "Wie schnell zeigt SEO Ergebnisse?", answer: "Das hängt von Ausgangslage, Wettbewerb und Umfang ab. Technische Verbesserungen können früh erkennbar sein, nachhaltige organische Entwicklung benötigt meist mehr Zeit." }, { question: "Ist SEO eine einmalige Aufgabe?", answer: "Eine solide Grundlage kann einmalig geschaffen werden. Märkte, Inhalte und Suchergebnisse verändern sich jedoch, weshalb regelmäßige Weiterentwicklung sinnvoll ist." }],
        ctaTitle: "Möchten Sie in relevanten Suchmomenten besser gefunden werden?", ctaBody: "Registrieren Sie sich und starten Sie Ihr Google-SEO-Projekt mit Empria Tech.", ctaPrimary: "SEO-Projekt starten", ctaSecondary: "Anmelden",
      },
      en: {
        metaTitle: "Google SEO for Businesses — Empria Tech", metaDescription: "Google SEO by Empria Tech: keyword strategy, technical SEO, on-page content and local visibility for sustainable organic growth.",
        eyebrow: "Empria Tech · Google SEO", title: "Google SEO", accent: "for relevant organic visibility.", intro: "We create the technical, structural and editorial foundation Google needs to understand your pages, helping potential customers find them in the search moments that matter.", imageAlt: "SEO analysis showing keyword data, technical reports and organic trends", primary: "Start an SEO project",
        overviewEyebrow: "A transparent search strategy", overviewTitle: "Visibility starts with search intent, not isolated keywords.", overviewBody: "We examine what your audience searches for, the questions behind each query and which page can provide the strongest answer. The result is a prioritized strategy rather than an unrelated task list.",
        capabilities: [{ title: "Keyword strategy", body: "Search themes are organized by relevance, intent and business value." }, { title: "Technical SEO", body: "Indexability, internal structure and technical signals are assessed." }, { title: "On-page SEO", body: "Titles, headings, content and internal links receive a clear purpose." }, { title: "Content planning", body: "Relevant pages and themes are developed around genuine questions." }, { title: "Local SEO", body: "Location-based searches and local relevance are addressed deliberately." }, { title: "Evaluation", body: "Progress and priorities are reviewed using transparent signals." }],
        deliverablesEyebrow: "Scope", deliverablesTitle: "The essential building blocks of sustainable SEO.", deliverables: ["Search market and competitor analysis", "Keyword and topic architecture", "Technical assessment", "On-page recommendations and optimization", "Search-intent-led content planning", "Prioritized continued improvement"],
        processEyebrow: "Our SEO process", processTitle: "Analyze, prioritize, implement and improve.", process: [{ number: "01", title: "Baseline", body: "We assess the website, market, content and existing organic signals." }, { number: "02", title: "Search strategy", body: "We organize relevant topics and define realistic priorities." }, { number: "03", title: "Optimization", body: "Technology, page structure and content are improved systematically." }, { number: "04", title: "Development", body: "Insights guide new content and the next useful improvements." }],
        outcomesEyebrow: "Impact", outcomesTitle: "Stronger conditions for organic growth.", outcomesBody: "SEO is a long-term discipline. We do not promise a fixed position; we create a dependable foundation for relevant visibility.", outcomes: [{ title: "Easier to understand", body: "Search engines can interpret topics, relationships and page purpose more clearly." }, { title: "More relevant content", body: "Pages align with genuine audience questions and decisions." }, { title: "Clear priorities", body: "Work follows a reasoned sequence rather than isolated tactics." }],
        relatedEyebrow: "Related services", relatedTitle: "SEO works harder with a strong website and coordinated campaigns.", faqEyebrow: "Google SEO FAQ", faqTitle: "Common questions about search optimization.", faqs: [{ question: "Does SEO guarantee first place on Google?", answer: "No. Rankings depend on many factors. Responsible SEO improves relevance and opportunity but cannot guarantee a fixed position." }, { question: "How quickly does SEO show results?", answer: "It depends on the starting point, competition and scope. Technical improvements may be visible early, while sustainable organic progress generally takes longer." }, { question: "Is SEO a one-time task?", answer: "A strong foundation can be created once, but markets, content and search results change, making regular development valuable." }],
        ctaTitle: "Ready to be found in more relevant search moments?", ctaBody: "Register and start your Google SEO project with Empria Tech.", ctaPrimary: "Start an SEO project", ctaSecondary: "Log in",
      },
    },
  },
  digitalMarketing: {
    path: "/digital-marketing", image: marketingImage, related: ["webdesign", "appDevelopment"],
    copy: {
      de: {
        metaTitle: "Digital Marketing für Unternehmen — Empria Tech", metaDescription: "Digital Marketing von Empria Tech: Kanalstrategie, Kampagnen, Content, Social Media, Landingpages und messbare Optimierung.",
        eyebrow: "Empria Tech · Digital Marketing", title: "Digital Marketing", accent: "mit Strategie und klarer Richtung.", intro: "Wir verbinden Kanäle, Inhalte und Kampagnen zu einem nachvollziehbaren System, das Ihre Marke sichtbar macht und Interessenten gezielt zu Ihrem Angebot führt.", imageAlt: "Digital-Marketing-Arbeitsplatz mit Kampagnenplanung, Content-Kalender und Leistungsdaten", primary: "Marketing-Projekt starten",
        overviewEyebrow: "Koordiniert statt beliebig", overviewTitle: "Die richtigen Botschaften über die richtigen Kanäle.", overviewBody: "Digitales Marketing ist mehr als regelmäßiges Veröffentlichen. Wir klären Zielgruppen, Ziele und die Rolle jedes Kanals, damit Inhalte und Kampagnen aufeinander einzahlen und Ihre Website als zentraler Anlaufpunkt funktioniert.",
        capabilities: [{ title: "Kanalstrategie", body: "Kanäle werden nach Zielgruppe, Aufgabe und realistischer Wirkung ausgewählt." }, { title: "Kampagnenplanung", body: "Botschaft, Ablauf, Zielseite und Messung werden zusammen gedacht." }, { title: "Content Marketing", body: "Nützliche Inhalte unterstützen Aufmerksamkeit, Vertrauen und Entscheidung." }, { title: "Social Media", body: "Themen und Formate schaffen eine konsistente, relevante Präsenz." }, { title: "Landingpages", body: "Fokussierte Seiten führen Besucher passend zur Kampagne weiter." }, { title: "Analyse & Optimierung", body: "Erkenntnisse werden genutzt, um nächste Maßnahmen gezielt zu verbessern." }],
        deliverablesEyebrow: "Leistungsumfang", deliverablesTitle: "Bausteine für strukturierte digitale Kommunikation.", deliverables: ["Zielgruppen- und Kanalplanung", "Kampagnenkonzept und Botschaften", "Content-Themen und Redaktionsstruktur", "Social-Media-Formate und Planung", "Landingpage-Konzeption", "Auswertung und iterative Optimierung"],
        processEyebrow: "Unser Marketing-Prozess", processTitle: "Von Zielen und Zielgruppen zu koordinierten Maßnahmen.", process: [{ number: "01", title: "Ausrichtung", body: "Wir klären Ziel, Zielgruppe, Angebot und die Rolle der digitalen Kanäle." }, { number: "02", title: "Kampagnenplan", body: "Wir verbinden Botschaften, Formate, Zeitplan und passende Zielseiten." }, { number: "03", title: "Umsetzung", body: "Inhalte und Kampagnenelemente werden konsistent vorbereitet und ausgespielt." }, { number: "04", title: "Lernen", body: "Ergebnisse werden ausgewertet und in die nächste Optimierungsrunde übertragen." }],
        outcomesEyebrow: "Wirkung", outcomesTitle: "Mehr Klarheit in Ihrer digitalen Vermarktung.", outcomesBody: "Der Schwerpunkt liegt auf einer verständlichen Strategie und sinnvoll verbundenen Maßnahmen – ohne erfundene Reichweiten- oder Umsatzversprechen.", outcomes: [{ title: "Konsistente Präsenz", body: "Botschaften und Gestaltung bleiben über relevante Kontaktpunkte hinweg erkennbar." }, { title: "Fokussierte Kampagnen", body: "Jede Maßnahme hat eine definierte Zielgruppe, Aufgabe und Zielseite." }, { title: "Bessere Entscheidungen", body: "Auswertung ersetzt Bauchgefühl durch nachvollziehbare nächste Schritte." }],
        relatedEyebrow: "Sinnvolle Ergänzungen", relatedTitle: "Kampagnen brauchen eine starke Website und organische Basis.", faqEyebrow: "Digital Marketing FAQ", faqTitle: "Häufige Fragen zu digitalen Kampagnen.", faqs: [{ question: "Welche Kanäle nutzt Empria Tech?", answer: "Die Auswahl richtet sich nach Zielgruppe, Angebot und Ziel. Dazu können Content, Social Media, Suchkanäle, E-Mail-Kommunikation und fokussierte Landingpages gehören." }, { question: "Muss mein Unternehmen auf jedem Kanal aktiv sein?", answer: "Nein. Wenige relevante und gut betreute Kanäle sind meist sinnvoller als eine unkoordinierte Präsenz überall." }, { question: "Wie wird der Erfolg bewertet?", answer: "Vor einer Kampagne werden passende Signale definiert. Die Auswertung richtet sich nach dem konkreten Ziel, etwa qualifizierten Besuchen, Anfragen oder Interaktion." }],
        ctaTitle: "Bereit für digitales Marketing mit klarer Richtung?", ctaBody: "Registrieren Sie sich und starten Sie Ihr Digital-Marketing-Projekt mit Empria Tech.", ctaPrimary: "Marketing-Projekt starten", ctaSecondary: "Anmelden",
      },
      en: {
        metaTitle: "Digital Marketing for Businesses — Empria Tech", metaDescription: "Digital marketing by Empria Tech: channel strategy, campaigns, content, social media, landing pages and measurable optimization.",
        eyebrow: "Empria Tech · Digital marketing", title: "Digital marketing", accent: "with strategy and clear direction.", intro: "We connect channels, content and campaigns in a transparent system that builds visibility and guides interested audiences toward your offer.", imageAlt: "Digital marketing workspace showing campaign planning, a content calendar and performance data", primary: "Start a marketing project",
        overviewEyebrow: "Coordinated, not arbitrary", overviewTitle: "The right messages through the right channels.", overviewBody: "Digital marketing is more than posting regularly. We clarify audiences, goals and each channel’s role so content and campaigns reinforce one another while your website remains the central destination.",
        capabilities: [{ title: "Channel strategy", body: "Channels are selected by audience, purpose and realistic potential." }, { title: "Campaign planning", body: "Message, journey, landing page and measurement are planned together." }, { title: "Content marketing", body: "Useful content supports attention, trust and informed decisions." }, { title: "Social media", body: "Themes and formats create a consistent, relevant presence." }, { title: "Landing pages", body: "Focused pages continue the campaign journey without distraction." }, { title: "Analysis & optimization", body: "Insights are used to improve the next round of activity." }],
        deliverablesEyebrow: "Scope", deliverablesTitle: "Building blocks for structured digital communication.", deliverables: ["Audience and channel planning", "Campaign concept and messaging", "Content themes and editorial structure", "Social media formats and planning", "Landing page concepts", "Evaluation and iterative optimization"],
        processEyebrow: "Our marketing process", processTitle: "From goals and audiences to coordinated activity.", process: [{ number: "01", title: "Direction", body: "We clarify the goal, audience, offer and role of each digital channel." }, { number: "02", title: "Campaign plan", body: "We connect messaging, formats, timing and relevant landing pages." }, { number: "03", title: "Delivery", body: "Content and campaign elements are prepared and delivered consistently." }, { number: "04", title: "Learn", body: "Results are evaluated and translated into the next round of improvement." }],
        outcomesEyebrow: "Impact", outcomesTitle: "Greater clarity across your digital marketing.", outcomesBody: "The focus is a coherent strategy and connected activity, without invented reach or revenue promises.", outcomes: [{ title: "Consistent presence", body: "Messaging and design remain recognizable across relevant touchpoints." }, { title: "Focused campaigns", body: "Every activity has a defined audience, purpose and destination." }, { title: "Better decisions", body: "Evaluation replaces guesswork with informed next steps." }],
        relatedEyebrow: "Related services", relatedTitle: "Campaigns need a strong website and organic foundation.", faqEyebrow: "Digital marketing FAQ", faqTitle: "Common questions about digital campaigns.", faqs: [{ question: "Which channels does Empria Tech work with?", answer: "The selection depends on the audience, offer and goal. It can include content, social media, search channels, email communication and focused landing pages." }, { question: "Does my company need to be active everywhere?", answer: "No. A smaller number of relevant, well-managed channels is generally more valuable than an uncoordinated presence everywhere." }, { question: "How is success evaluated?", answer: "Relevant signals are defined before a campaign. Evaluation follows the specific goal, such as qualified visits, enquiries or engagement." }],
        ctaTitle: "Ready for digital marketing with clear direction?", ctaBody: "Register and start your digital marketing project with Empria Tech.", ctaPrimary: "Start a marketing project", ctaSecondary: "Log in",
      },
    },
  },
  appDevelopment: {
    path: "/app-entwicklung", image: appImage, related: ["webdesign", "digitalMarketing"],
    copy: {
      de: {
        metaTitle: "App-Entwicklung für Unternehmen — Empria Tech", metaDescription: "Individuelle App-Entwicklung von Empria Tech: Web-Apps, iOS- und Android-Apps, Kundenportale, Dashboards und Schnittstellen.",
        eyebrow: "Empria Tech · App-Entwicklung", title: "App-Entwicklung", accent: "für Web und Mobile.", intro: "Wir entwickeln individuelle Anwendungen, die Abläufe vereinfachen, Kunden besser einbinden und mit Ihrem Unternehmen wachsen.", imageAlt: "Laptop mit Web-App-Dashboard und Smartphone mit mobiler App", primary: "App-Projekt starten",
        overviewEyebrow: "Software mit klarem Zweck", overviewTitle: "Anwendungen, die echte Aufgaben lösen.", overviewBody: "Ob Kundenportal, internes Tool oder mobile App: Wir beginnen mit den Abläufen und Menschen, die die Anwendung nutzen werden, und entwickeln daraus eine verständliche, stabile Lösung.",
        capabilities: [{ title: "Web-Apps", body: "Browserbasierte Anwendungen, die ohne Installation auf allen Geräten laufen." }, { title: "iOS- & Android-Apps", body: "Mobile Apps mit durchdachter Bedienung für Smartphone und Tablet." }, { title: "Kundenportale", body: "Sichere Bereiche, in denen Kunden Daten, Dokumente und Aufträge einsehen." }, { title: "Dashboards & interne Tools", body: "Übersichtliche Werkzeuge für Teams, Auswertungen und Verwaltung." }, { title: "Schnittstellen & Integrationen", body: "Anbindung bestehender Systeme, Zahlungsanbieter und Datenquellen." }, { title: "Wartung & Weiterentwicklung", body: "Updates, Verbesserungen und neue Funktionen nach dem Start." }],
        deliverablesEyebrow: "Leistungsumfang", deliverablesTitle: "Bausteine für eine belastbare Anwendung.", deliverables: ["Anforderungsanalyse und Funktionsplanung", "UX-Konzept und klickbare Entwürfe", "UI-Design für Web und Mobile", "Entwicklung von Oberfläche und Datenlogik", "Benutzerkonten, Rollen und Datenschutz", "Tests, Veröffentlichung und Betreuung"],
        processEyebrow: "Unser Entwicklungsprozess", processTitle: "Von der Idee zur laufenden Anwendung.", process: [{ number: "01", title: "Analyse", body: "Wir klären Ziele, Nutzer, Abläufe und den sinnvollen Funktionsumfang." }, { number: "02", title: "Konzept & Design", body: "Nutzerwege und Oberflächen werden geplant und gemeinsam abgestimmt." }, { number: "03", title: "Entwicklung", body: "Die Anwendung entsteht in überprüfbaren Schritten mit regelmäßigem Feedback." }, { number: "04", title: "Start & Betreuung", body: "Nach Tests geht die App live und wird gezielt weiterentwickelt." }],
        outcomesEyebrow: "Wirkung", outcomesTitle: "Weniger Handarbeit, bessere Erfahrung.", outcomesBody: "Der Fokus liegt auf praktischem Nutzen und solider Technik – ohne überladene Funktionen oder unrealistische Versprechen.", outcomes: [{ title: "Effizientere Abläufe", body: "Wiederkehrende Aufgaben werden vereinfacht oder automatisiert." }, { title: "Bessere Kundenbindung", body: "Kunden erhalten einen klaren, digitalen Zugang zu Ihren Leistungen." }, { title: "Skalierbare Basis", body: "Die Anwendung kann mit neuen Anforderungen sauber wachsen." }],
        relatedEyebrow: "Sinnvolle Ergänzungen", relatedTitle: "Eine starke App profitiert von Website und Reichweite.", faqEyebrow: "App-Entwicklung FAQ", faqTitle: "Häufige Fragen zur App-Entwicklung.", faqs: [{ question: "Web-App oder native App – was ist sinnvoller?", answer: "Das hängt von Zielgruppe, Funktionen und Budget ab. Web-Apps sind schnell überall verfügbar, native Apps bieten tiefere Geräteintegration. Wir beraten dazu in der Analysephase." }, { question: "Kann eine bestehende Software erweitert werden?", answer: "Ja. Nach einer technischen Prüfung können bestehende Anwendungen gezielt erweitert oder angebunden werden." }, { question: "Wer betreut die App nach dem Start?", answer: "Auf Wunsch übernimmt Empria Tech Wartung, Updates und Weiterentwicklung." }],
        ctaTitle: "Bereit für Ihre eigene Anwendung?", ctaBody: "Registrieren Sie sich und starten Sie Ihr App-Projekt mit Empria Tech.", ctaPrimary: "App-Projekt starten", ctaSecondary: "Anmelden",
      },
      en: {
        metaTitle: "App Development for Businesses — Empria Tech", metaDescription: "Custom app development by Empria Tech: web apps, iOS and Android apps, customer portals, dashboards and integrations.",
        eyebrow: "Empria Tech · App development", title: "App development", accent: "for web and mobile.", intro: "We build custom applications that simplify operations, engage customers and grow with your business.", imageAlt: "Laptop showing a web app dashboard and a smartphone showing a mobile app", primary: "Start an app project",
        overviewEyebrow: "Software with a clear purpose", overviewTitle: "Applications that solve real tasks.", overviewBody: "Whether a customer portal, internal tool or mobile app, we start with the workflows and people who will use it and turn them into a clear, reliable solution.",
        capabilities: [{ title: "Web apps", body: "Browser-based applications that run on every device without installation." }, { title: "iOS & Android apps", body: "Mobile apps with thoughtful usability for phones and tablets." }, { title: "Customer portals", body: "Secure areas where customers view data, documents and orders." }, { title: "Dashboards & internal tools", body: "Clear tools for teams, reporting and administration." }, { title: "APIs & integrations", body: "Connecting existing systems, payment providers and data sources." }, { title: "Maintenance & growth", body: "Updates, improvements and new features after launch." }],
        deliverablesEyebrow: "Scope", deliverablesTitle: "Building blocks for a dependable application.", deliverables: ["Requirements analysis and feature planning", "UX concept and clickable prototypes", "UI design for web and mobile", "Front-end and data logic development", "User accounts, roles and data protection", "Testing, launch and ongoing support"],
        processEyebrow: "Our development process", processTitle: "From idea to running application.", process: [{ number: "01", title: "Analysis", body: "We clarify goals, users, workflows and a sensible feature scope." }, { number: "02", title: "Concept & design", body: "User journeys and screens are planned and agreed together." }, { number: "03", title: "Development", body: "The application is built in reviewable steps with regular feedback." }, { number: "04", title: "Launch & support", body: "After testing the app goes live and keeps improving." }],
        outcomesEyebrow: "Impact", outcomesTitle: "Less manual work, a better experience.", outcomesBody: "The focus is practical value and solid engineering, without bloated features or unrealistic promises.", outcomes: [{ title: "More efficient workflows", body: "Recurring tasks are simplified or automated." }, { title: "Stronger customer relationships", body: "Customers get clear digital access to your services." }, { title: "Scalable foundation", body: "The application can grow cleanly with new requirements." }],
        relatedEyebrow: "Related services", relatedTitle: "A strong app benefits from a website and reach.", faqEyebrow: "App development FAQ", faqTitle: "Common questions about app development.", faqs: [{ question: "Web app or native app — which is better?", answer: "It depends on audience, features and budget. Web apps are quickly available everywhere; native apps offer deeper device integration. We advise during analysis." }, { question: "Can existing software be extended?", answer: "Yes. After a technical review, existing applications can be extended or integrated." }, { question: "Who looks after the app after launch?", answer: "On request, Empria Tech handles maintenance, updates and further development." }],
        ctaTitle: "Ready for your own application?", ctaBody: "Register and start your app project with Empria Tech.", ctaPrimary: "Start an app project", ctaSecondary: "Log in",
      },
    },
  },
};

export const serviceNames: Record<ServiceKey, Record<HomepageLanguage, string>> = {
  webdesign: { de: "Webdesign", en: "Web design" },
  googleSeo: { de: "Google SEO", en: "Google SEO" },
  digitalMarketing: { de: "Digital Marketing", en: "Digital marketing" },
  appDevelopment: { de: "App-Entwicklung", en: "App development" },
};